[package]
name = "test1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "stepwise"
path = "stepwise.rs"

[[bin]]
name = "mequeue"
path = "mequeue.rs"

[[bin]]
name = "artemis"
path = "artemis.rs"

[dependencies]
stepwise = { git = "https://github.com/mekosko/mequeue" }
artemis-core = { git = "https://github.com/mekosko/artemis", branch = "deadlock" }
mequeue = { git = "https://github.com/mekosko/mequeue", branch = "ref_check" }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
futures = "0.3"
anyhow = "1"
tracing-subscriber = "0.3"
